image: busybox

# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

#include: '.gitlab-ci-runners-templates.yml'

stages:
  - Static-analysis
  - Build
  - Test
  - Pack

include:
  - template: Auto-DevOps.gitlab-ci.yml
  - template: ".gitlab-ci-runners-templates.yml"

# JOBS
pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH


# Builds
build-Linux-Static-analysis:
   extends: .linuxJobTemplate
   stage: Static-analysis
   variables:
     USE_CLANG: "true"
     USE_CLAZY: "true"
   script:
     - ruby static-analysis.rb
   artifacts:
     paths:
       - build
     expire_in: 15 m

build-Linux:
   extends: .linuxJobTemplate
   stage: Build
   needs: ["build-Linux-Static-analysis"]
   variables:
     SHOULD_BUILD: "true"
   script:
     - ruby targets/linux/runPipeline.rb
   artifacts:
     paths:
       - build/linux
     expire_in: 15 m


build-macOS:
  extends: .macOSJobTemplate
  stage: Build
  variables:
    SHOULD_BUILD: "true"
  script:
    - ruby targets/macOS/runPipeline.rb
  artifacts:
    paths:
      - build/macOS
    expire_in: 15 m
